IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)   
    ActionOverride("enteri01",MoveToPoint([522.497]))
    Wait(8)
    ActionOverride("enteri01",FaceObject("bgctboss"))
    ActionOverride("bgctboss",FaceObject("enteri01"))
    Wait(2)
    DisplayStringHead("enteri01",@10014)
    Wait(5)
    DisplayStringHead("bgctboss",@10015)
    Wait(11)
    DisplayStringHead("enteri01",@10016)
    Wait(24)
    StartCutScene("bgarive4")
END

