IF
  Global("tz_wolfsee","LOCALS",0)
  See([PC])
  Range([PC],15)
THEN
  RESPONSE #100
    SetGlobal("tz_wolfsee","LOCALS",1)
    StartDialogNoSet([PC])
END

IF
  Heard([ANYONE],111)
THEN
  RESPONSE #100
    MoveToObject(NearestEnemyOf(Myself))
END

IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  !Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END

